name: Trigger Sync to ThenGB.github.io

on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch on ThenGB.github.io
        env:
          GH_TOKEN: ${{ secrets.THENGB_IO_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/ThenGB/ThenGB.github.io/dispatches \
            -d '{"event_type": "sync-gyschordweb"}'
