name: Sync gyschordweb to this repo

on:
  schedule:
    - cron: '0 17 * * *' # Setiap hari jam 00:00 UTC+7 (17:00 UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone gyschordweb repository
        env:
          GYSCHORDWEB_PAT: ${{ secrets.GYSCHORDWEB_PAT }}
        run: |
          git clone https://$GYSCHORDWEB_PAT@github.com/ThenGB/gyschordweb.git temp_gyschordweb

      - name: Sync files from gyschordweb ke folder gyschordweb
        run: |
          mkdir -p gyschordweb
          rsync -av --delete temp_gyschordweb/ gyschordweb/ --exclude .git
          rm -rf temp_gyschordweb

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Sync from gyschordweb"
          git push origin main
